### ISSUE TITLE
Stable release date

### ISSUE THREAD

**Issue by es-repo** [okta/okta-oidc-xamarin#17]
This is not a  feature request. 

The latest release [notes ](https://github.com/okta/okta-oidc-xamarin/releases) says that stable release will be in few weeks. 6 months last since then... Is this library abandoned or do you still plan to release a stable version of the package?

**Comment by bryanapellanes-okta** [comment]
@es-repo,
Thanks for your inquiry.  Due to priorities shifting internally, initial production release has been pushed back and we are currently planning to release the first version with login and logout functionality in November 🤞.

**Comment by es-repo** [comment]
@bryanapellanes-okta Thanks for the status update. Do you plan to implement silent login functionality in this first version release?

**Comment by bryanapellanes-okta** [comment]
@es-repo,
The login functionality of the first release will be an implementation of the OIDC flow.

**Comment by bryanapellanes-okta** [comment]
We are re-evaluating, internally, what requirements must be met in order to consider this Sdk stable.  It is unclear when the "beta" moniker of this Sdk will be removed but we will continue to release features as priorities dictate.
