### ISSUE TITLE
OidcClient not found

### ISSUE THREAD

**Issue by GeforceA** [okta/okta-oidc-xamarin#38]
I am very new to both okta and Github so I might miss something that is very obvious to other people.

Installed the prerelease 02, follow the guide to add in 
            OktaContext.Init(new OidcClient(this, OktaConfig.LoadFromXmlStream(Assets.Open("OktaConfig.xml"))));
            OktaContext.AddSignInCompletedListener((sender, args) => Shell.Current.GoToAsync("//ProfilePage"));
            OktaContext.AddSignOutCompletedListener((sender, args) => Shell.Current.GoToAsync("//ProfilePage"));
in the OnCreate method.  and the VS reports OidcClient/OktaConfig/Shell does not exit in the current context.  

Searched the source code here and found there is an AndroidOidcClient class instead, but I don't see it with the Pre Release 2.  Please advise how should I proceed with this library.

Thanks.
Jun

**Comment by bryanapellanes-okta** [comment]
@GeforceA,
Thanks for reaching out.  We are actively working on the next release; the branch with instructions relevant to the current pre-release can be found here: https://github.com/okta/okta-oidc-xamarin/tree/v1.0.0-beta02

Please note that there are a number of fixes in progress that we expect to include in the next release, and recommend not using the beta02 package at this time however it is available for your reference.

**Comment by bryanapellanes-okta** [comment]
@GeforceA,
Stay tuned for the next release.  I'll update here when it is published.

**Comment by Giorgi** [comment]
@bryanapellanes-okta Is there any eta for the next release?

**Comment by bryanapellanes-okta** [comment]
@Giorgi,
Thanks for reaching out!  I'm hoping to publish the next release soon, the code is currently in review here: https://github.com/okta/okta-oidc-xamarin/pull/41

Once reviewed and merged the nuget packages will be published minutes later.  Feel free to watch the pull request for updates.

If you are so inclined you can get early access to the nuget packages by downloading them from here: https://github.com/okta/okta-oidc-xamarin/tree/OKTA-360964-release-v1.0.0/nuget/packages

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
@GeforceA @Giorgi,
The v1.0.0 release was published.  

The README is updated and describes how to get started with the new release: https://github.com/okta/okta-oidc-xamarin#usage-guide

Example applications are also available for reference here: https://github.com/okta/okta-oidc-xamarin/tree/master/Okta.Xamarin/Samples/xamarin
