### ISSUE TITLE
Okta endpoint url without AuthorizationServerId

### ISSUE THREAD

**Issue by Romgua** [okta/okta-oidc-xamarin#80]
Hi,

I need to use this type of endpoint :

- $"{OktaDomain}/oauth2/v1/authorize"
- $"{OktaDomain}/oauth2/v1/logout"
- $"{OktaDomain}/oauth2/v1/token"

=> So without _AuthorizationServerId_, how can I do ?

Thanks,
Romain

**Comment by andriizhegurov-okta** [comment]
Hi @Romgua, `AuthorizationServerId` is an optional configuration property, you can set it to an empty string if you want URIs like that to be generated.

**Comment by Romgua** [comment]
Oh yes, sorry. I thought I tried that option.
Thank you for your answer, it solved my problem.
