### ISSUE TITLE
Publish 3.0.1 to Nuget?

### ISSUE THREAD

**Issue by kensykora** [okta/okta-oidc-xamarin#83]
Hey, Thanks for releasing 3.0.1 with those fixes. I'm eagerly anticipating pulling them in so I don't need to have a forked version of this repo via a git submodule anymore :) 

I've noticed on the nuget page, the 3.0.1 package still is not released. Is that being planned to go out soon? https://www.nuget.org/packages/Okta.Xamarin/

**Comment by bryanapellanes-okta** [comment]
@kensykora,
The 3.0.1 packages are now available on nug.org: https://www.nuget.org/packages?q=Okta.Xamarin.  Feel free to reach out again if you have further questions, comments, suggestions or concerns.

Thanks for using Okta!
