### ISSUE TITLE
[iOS] SetFlags must be called before Init

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [okta/okta-oidc-xamarin#96]
### Describe the bug?

I'm getting the 'SetFlags must be called before Init' error in the iOS platform alone, though I set flags before xamarin.forms init.

Call Stace:

  at Xamarin.Forms.Forms.SetFlags (System.String[] flags) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Forms.cs:184
  at Okta.Xamarin.iOS.OktaAppDelegate`1[TApp].FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00001] in <eee6f59488ed401f92289d2f3ae0507e>:0
  at PPT.CentralPark.Mobile.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0007f] in /Users/suyash.sadh/central-park-mobile/PPT.CentralPark.Mobile/PPT.CentralPark.Mobile.iOS/AppDelegate.cs:42
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:73
  at PPT.CentralPark.Mobile.iOS.Application.Main (System.String[] args) [0x00001] in /Users/suyash.sadh/central-park-mobile/PPT.CentralPark.Mobile/PPT.CentralPark.Mobile.iOS/Main.cs:17

AppDelegate.cs
![image](https://user-images.githubusercontent.com/44390143/185918137-2dba0426-f7c5-46d4-8e3a-b9a4097cc40f.png)

App.xaml.cs
![image](https://user-images.githubusercontent.com/44390143/185918287-afd6b6e8-c62f-4c2a-bcb7-a71d4cf25c51.png)

Attached are both files snaps for your reference.

This error does not occur when appdelegate.cs derived from FormsApplicationDelegate.

### What is expected to happen?

The app should load properly without error like set flags prior to xamarin forms

### What is the actual behavior?

 'SetFlags must be called before Init' error is thrown in the iOS platform

### Reproduction Steps?

Run the simple okta configured xamarin app with reference to attached appdelegate and app.xaml.cs.
Before deploy, y will able to see the error. 

### Dotnet Information

Microsoft Visual Studio Enterprise 2019
Version 16.11.18
VisualStudio.16.Release/16.11.18+32802.440
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00434-00051-42725-AA725
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0.300
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.126+g11d4cf0d0c.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@47

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### SDK Version

okta.sdk 3.1.0

**Comment by GnanaPriyaNamasivayam** [comment]
@bryanapellanes-okta Thanks for the update. 
If you take a look at the call stack, it's from oktaAppDelegate. That's the reason I have posted is the call stack comes from your source. 

Could you please look into this in detail and share some suggestions.

**Comment by bryanapellanes-okta** [comment]
@GnanaPriyaNamasivayam Sorry I missed that detail.  The latest release of the Okta.Xamarin Sdk deprecates OktaAppdelegate: https://github.com/okta/okta-oidc-xamarin/blob/master/Okta.Xamarin/Okta.Xamarin.iOS/OktaAppDelegate.cs#L18
Please see the recommended approach here: https://github.com/okta/samples-xamarin/blob/c61b3dfff7ca66961e39d03ea26249a3a23743bd/Okta.Xamarin.Demo.iOS/AppDelegate.cs#L33

**Comment by GnanaPriyaNamasivayam** [comment]
Still facing the same error even with the initialization.
![image](https://user-images.githubusercontent.com/44390143/186085354-923895a3-ca2e-4a06-884b-8234f2fab64e.png)

**Comment by GnanaPriyaNamasivayam** [comment]
<img width="575" alt="Screenshot 2022-08-23 at 4 33 08 PM" src="https://user-images.githubusercontent.com/44390143/186142477-25fcc4cb-c79b-44fc-8248-5a87bf48cb70.png">
With the above code setup, I'm able to enter the login screen.

One question, Is it necessary to initiate a collection view in AppDelegae of my project? Asking this because I see you have a collection view initiated in your source.

**Comment by bryanapellanes-okta** [comment]
@GnanaPriyaNamasivayam I'm glad you got that working!  [The line that specifies "CollectionView_Experimental"](https://github.com/okta/samples-xamarin/blob/c61b3dfff7ca66961e39d03ea26249a3a23743bd/Okta.Xamarin.Demo.iOS/AppDelegate.cs#L27) was included in the template that the sample is based on.  It isn't explicitly required, you can read more about it here https://devblogs.microsoft.com/xamarin/xamarin-forms-4-3-introducing-collectionview/.

Feel free to open a new issue if other challenges arise.  Thanks for using Okta!
