### ISSUE TITLE
[iOS] Object disposed exception on signout using SignOutCommand

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [okta/okta-oidc-xamarin#97]
### Describe the bug?

In the xamarin application, below is how I sign out from the app.
![image](https://user-images.githubusercontent.com/44390143/186160699-277150b5-7f84-4ed4-8d49-938334cb6943.png)

The same code logs out properly in android but iOS throws an object disposed of exception from the okta sdk source before **OnSignOutCompleted** call-back method hits.

**Call stack**
at Foundation.NSObject.get_SuperHandle () [0x00012] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:556
  at UIKit.UIViewController.PresentViewController (UIKit.UIViewController viewControllerToPresent, System.Boolean animated, System.Action completionHandler) [0x00059] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:716
  at UIKit.UIViewController.PresentViewControllerAsync (UIKit.UIViewController viewControllerToPresent, System.Boolean animated) [0x00011] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:725
  at **Okta.Xamarin.iOS.iOsOidcClient.LaunchBrowser** (System.String url) [0x00018] in <eee6f59488ed401f92289d2f3ae0507e>:0
  at Okta.Xamarin.OidcClient.SignOutOfOktaAsync (Okta.Xamarin.IOktaStateManager stateManager) [0x0008d] in <d9e3d3ec9e4f4c3cad3625ba84244063>:0
  at **Okta.Xamarin.OktaContext.SignOutAsync** (Okta.Xamarin.IOidcClient oidcClient) [0x0004e] in <d9e3d3ec9e4f4c3cad3625ba84244063>:0
  at Okta.Xamarin.ViewModels.SignOutCommand+<>c.<.ctor>b__0_0 () [0x0008a] in <d9e3d3ec9e4f4c3cad3625ba84244063>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:73
  at PPT.CentralPark.Mobile.iOS.Application.Main (System.String[] args) [0x00001] in /Users/suyash.sadh/central-park-mobile/PPT.CentralPark.Mobile/PPT.CentralPark.Mobile.iOS/Main.cs:17

Snapshot:

![Uploading image.png…]()

### What is expected to happen?

Logout should happen seemlessly.

### What is the actual behavior?

Signoutcommand crashes the app with object dispose exception.

### Reproduction Steps?

Hope the call stack helps you to figure that out.
In addition to that below are the NuGets we use in our project.
iOS
![image](https://user-images.githubusercontent.com/44390143/186162070-fc699566-eade-48ab-a836-f857eff10bf7.png)
 PCL
![image](https://user-images.githubusercontent.com/44390143/186162170-cfa826b5-390e-47d4-8c04-208322b111c1.png)
I don't have time to duplicate a sample project similar to mine to replicate. 

 

### Dotnet Information

Microsoft Visual Studio Enterprise 2019
Version 16.11.18
VisualStudio.16.Release/16.11.18+32802.440
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Enterprise

Visual C++ 2019   00434-00051-42725-AA725
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0.300
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.126+g11d4cf0d0c.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@47

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### SDK Version

3.1.0 latest

**Comment by laura-rodriguez** [comment]
Hi @GnanaPriyaNamasivayam,

Thanks for reporting this issue. Our team will review it soon as possible.

**Comment by bryanapellanes-okta** [comment]
@GnanaPriyaNamasivayam Thanks for reaching out! I've added an internal ticket for investigation.  This will need to be prioritized against other work.

**Comment by GnanaPriyaNamasivayam** [comment]
I have also tried to sign out via the normal button command with,
 await OktaContext.Current.SignOutAsync();
and noticed that the SignOutCompleted event is not getting fired after the SignOutStarted event.
After the SignOutStarted event hits, the app throws an object disposed of exception.

Can you prioritize it as high and look into this? Any workaround or suggestions to resolve this will be helpful.

**Comment by GnanaPriyaNamasivayam** [comment]
Attached simple sample to replicate the issue.
Update Info.plist, Entitlement.plist, oktaconfig.plist based on your app.
Restore the package to deploy.
**Steps to replicate:**
1. Login with your credentials
2. In dashboard, open flyout layout 
3. tap logout - ODE will occur.

[OKTASDK_IssueApp.zip](https://github.com/okta/okta-oidc-xamarin/files/9430561/OKTASDK_IssueApp.zip)

**Comment by GnanaPriyaNamasivayam** [comment]
Hi @bryanapellanes-okta ,
Hope you get a chance to debug the issue with the attached sample.
Currently, this issue is blocking our iOS release. Could you please consider this a high priority and provide an ETA or at least
a workaround to resolve this issue?  

Any help from your side will be appreciable.

**Comment by bryanapellanes-okta** [comment]
@GnanaPriyaNamasivayam Sorry for the delay on this.  Work on this issue will begin shortly (this week).  Once I reproduce the issue a solution should follow soon after.  Thanks for your patience and I apologize for the inconvenience.
